import { ProviderPreset } from '../types/provider';

export const PROVIDER_PRESETS: ProviderPreset[] = [
  {
    id: 'aws',
    name: 'AWS S3',
    category: 'cloud',
    defaultRegion: 'us-east-1',
    forcePathStyle: false,
    requiresEndpoint: false,
    credentialsProfileDefault: 'default',
    description: 'Amazon Web Services S3 Storage',
  },
  {
    id: 'minio',
    name: 'MinIO (Self-Hosted)',
    category: 'self-hosted',
    defaultEndpoint: 'http://localhost:9000',
    defaultRegion: 'us-east-1',
    forcePathStyle: true,
    requiresEndpoint: true,
    credentialsProfileDefault: 'minio',
    description: 'High performance object storage for self-hosted deployments',
  },
  {
    id: 'oci',
    name: 'OCI Object Storage',
    category: 'cloud',
    defaultRegion: 'us-ashburn-1',
    forcePathStyle: true,
    requiresEndpoint: true,
    credentialsProfileDefault: 'oci',
    description: 'Oracle Cloud Infrastructure S3 Compatible API',
  },
  {
    id: 'r2',
    name: 'Cloudflare R2',
    category: 'cloud',
    defaultEndpoint: 'https://<account_id>.r2.cloudflarestorage.com',
    defaultRegion: 'auto',
    forcePathStyle: false,
    requiresEndpoint: true,
    credentialsProfileDefault: 'r2',
    description: 'Zero egress fee object storage by Cloudflare',
  },
  {
    id: 'wasabi',
    name: 'Wasabi Hot Cloud Storage',
    category: 'cloud',
    defaultEndpoint: 'https://s3.us-east-1.wasabisys.com',
    defaultRegion: 'us-east-1',
    forcePathStyle: false,
    requiresEndpoint: true,
    credentialsProfileDefault: 'wasabi',
    description: 'High performance S3-compatible cloud storage',
  },
  {
    id: 'backblaze',
    name: 'Backblaze B2',
    category: 'cloud',
    defaultEndpoint: 'https://s3.us-west-004.backblazeb2.com',
    defaultRegion: 'us-west-004',
    forcePathStyle: false,
    requiresEndpoint: true,
    credentialsProfileDefault: 'b2',
    description: 'S3 compatible cloud object storage by Backblaze',
  },
  {
    id: 'localstack',
    name: 'LocalStack',
    category: 'self-hosted',
    defaultEndpoint: 'http://localhost:4566',
    defaultRegion: 'us-east-1',
    forcePathStyle: true,
    requiresEndpoint: true,
    credentialsProfileDefault: 'localstack',
    description: 'Local AWS cloud stack developer emulator',
  },
  {
    id: 'custom',
    name: 'Custom S3 / Garage / Ceph',
    category: 'custom',
    defaultEndpoint: 'http://localhost:9000',
    defaultRegion: 'us-east-1',
    forcePathStyle: true,
    requiresEndpoint: true,
    credentialsProfileDefault: 'custom',
    description: 'Any generic S3-compatible server, Garage, Ceph, SeaweedFS, etc.',
  },
];

export function getPresetById(id: string): ProviderPreset {
  return PROVIDER_PRESETS.find((p) => p.id === id) || PROVIDER_PRESETS[0];
}
